title: Fatima's Personal Website
description: My portfolio site

# Navigation items (custom configuration)
nav_items:
  - name: Home
    url: "#navigation-bar"
  - name: About
    url: "#about"
  - name: Projects
    url: "#Projects"
  - name: Contact
    url: "#contact"